# --- AĞ SERVİSİ (Health check için gerekli) ---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
# --- DAĞITIM ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: kube-stock-notification-service:latest
        imagePullPolicy: Never # Mac'imizdeki imajı kullan
        env:
        - name: RABBITMQ_URL
          value: "amqp://rabbitmq:5672" # Postanenin K8s içindeki adresi